//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IllerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IllerIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorModel", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Core.ServiceContract")]
    public partial class ErrorModel : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IllerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IllerCevap : object
    {
        
        private int HataKoduField;
        
        private ServiceReference1.IlDTO[] IllerField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IlDTO[] Iller
        {
            get
            {
                return this.IllerField;
            }
            set
            {
                this.IllerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class IlDTO : object
    {
        
        private int IdField;
        
        private string IlAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlAdi
        {
            get
            {
                return this.IlAdiField;
            }
            set
            {
                this.IlAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlcelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IlcelerIstek : object
    {
        
        private int IlIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId
        {
            get
            {
                return this.IlIdField;
            }
            set
            {
                this.IlIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlcelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IlcelerCevap : object
    {
        
        private int HataKoduField;
        
        private ServiceReference1.IlceDTO[] IlcelerField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IlceDTO[] Ilceler
        {
            get
            {
                return this.IlcelerField;
            }
            set
            {
                this.IlcelerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlceDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class IlceDTO : object
    {
        
        private int IdField;
        
        private string IlceAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlceAdi
        {
            get
            {
                return this.IlceAdiField;
            }
            set
            {
                this.IlceAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class BeldelerIstek : object
    {
        
        private int IlceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId
        {
            get
            {
                return this.IlceIdField;
            }
            set
            {
                this.IlceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class BeldelerCevap : object
    {
        
        private ServiceReference1.BeldeDTO[] BeldelerField;
        
        private int HataKoduField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BeldeDTO[] Beldeler
        {
            get
            {
                return this.BeldelerField;
            }
            set
            {
                this.BeldelerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class BeldeDTO : object
    {
        
        private string BeldeAdiField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeldeAdi
        {
            get
            {
                return this.BeldeAdiField;
            }
            set
            {
                this.BeldeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class UlkelerIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class UlkelerCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private ServiceReference1.UlkeDTO[] UlkelerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.UlkeDTO[] Ulkeler
        {
            get
            {
                return this.UlkelerField;
            }
            set
            {
                this.UlkelerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class UlkeDTO : object
    {
        
        private int IdField;
        
        private string UlkeAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UlkeAdi
        {
            get
            {
                return this.UlkeAdiField;
            }
            set
            {
                this.UlkeAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class HalIciIsyeriIstek : object
    {
        
        private string TcKimlikVergiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo
        {
            get
            {
                return this.TcKimlikVergiNoField;
            }
            set
            {
                this.TcKimlikVergiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class HalIciIsyeriCevap : object
    {
        
        private int HataKoduField;
        
        private ServiceReference1.HalIciIsyeriDTO[] IsyerleriField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.HalIciIsyeriDTO[] Isyerleri
        {
            get
            {
                return this.IsyerleriField;
            }
            set
            {
                this.IsyerleriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class HalIciIsyeriDTO : object
    {
        
        private string HalAdiField;
        
        private int HalIdField;
        
        private int IdField;
        
        private string IsyeriAdiField;
        
        private string TcKimlikVergiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HalAdi
        {
            get
            {
                return this.HalAdiField;
            }
            set
            {
                this.HalAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HalId
        {
            get
            {
                return this.HalIdField;
            }
            set
            {
                this.HalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsyeriAdi
        {
            get
            {
                return this.IsyeriAdiField;
            }
            set
            {
                this.IsyeriAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo
        {
            get
            {
                return this.TcKimlikVergiNoField;
            }
            set
            {
                this.TcKimlikVergiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTurleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IsletmeTurleriIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTurleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class IsletmeTurleriCevap : object
    {
        
        private int HataKoduField;
        
        private ServiceReference1.IsletmeTuruDTO[] IsletmeTurleriField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IsletmeTuruDTO[] IsletmeTurleri
        {
            get
            {
                return this.IsletmeTurleriField;
            }
            set
            {
                this.IsletmeTurleriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTuruDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class IsletmeTuruDTO : object
    {
        
        private int IdField;
        
        private string IsletmeTuruAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsletmeTuruAdi
        {
            get
            {
                return this.IsletmeTuruAdiField;
            }
            set
            {
                this.IsletmeTuruAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepolarIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class DepolarIstek : object
    {
        
        private string TcKimlikVergiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo
        {
            get
            {
                return this.TcKimlikVergiNoField;
            }
            set
            {
                this.TcKimlikVergiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepolarCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class DepolarCevap : object
    {
        
        private ServiceReference1.DepoDTO[] DepolarField;
        
        private int HataKoduField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DepoDTO[] Depolar
        {
            get
            {
                return this.DepolarField;
            }
            set
            {
                this.DepolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepoDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class DepoDTO : object
    {
        
        private string AdresField;
        
        private int BeldeIdField;
        
        private string DepoAdiField;
        
        private bool HalicimiField;
        
        private int IdField;
        
        private int IlIdField;
        
        private int IlceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BeldeId
        {
            get
            {
                return this.BeldeIdField;
            }
            set
            {
                this.BeldeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepoAdi
        {
            get
            {
                return this.DepoAdiField;
            }
            set
            {
                this.DepoAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Halicimi
        {
            get
            {
                return this.HalicimiField;
            }
            set
            {
                this.HalicimiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId
        {
            get
            {
                return this.IlIdField;
            }
            set
            {
                this.IlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId
        {
            get
            {
                return this.IlceIdField;
            }
            set
            {
                this.IlceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class SubelerIstek : object
    {
        
        private string TcKimlikVergiNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo
        {
            get
            {
                return this.TcKimlikVergiNoField;
            }
            set
            {
                this.TcKimlikVergiNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    public partial class SubelerCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private ServiceReference1.SubeDTO[] SubelerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SubeDTO[] Subeler
        {
            get
            {
                return this.SubelerField;
            }
            set
            {
                this.SubelerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    public partial class SubeDTO : object
    {
        
        private string AdresField;
        
        private int BeldeIdField;
        
        private int IdField;
        
        private int IlIdField;
        
        private int IlceIdField;
        
        private int IsyeriTuruField;
        
        private string SubeAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BeldeId
        {
            get
            {
                return this.BeldeIdField;
            }
            set
            {
                this.BeldeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId
        {
            get
            {
                return this.IlIdField;
            }
            set
            {
                this.IlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId
        {
            get
            {
                return this.IlceIdField;
            }
            set
            {
                this.IlceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsyeriTuru
        {
            get
            {
                return this.IsyeriTuruField;
            }
            set
            {
                this.IsyeriTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeAdi
        {
            get
            {
                return this.SubeAdiField;
            }
            set
            {
                this.SubeAdiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gtb.gov.tr//WebServices", ConfigurationName="ServiceReference1.IGenelService")]
    public interface IGenelService
    {
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIller", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIllerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IllerCevap> GenelServisIllerAsync(ServiceReference1.BaseRequestMessageOf_IllerIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIlceler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIlcelerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IlcelerCevap> GenelServisIlcelerAsync(ServiceReference1.BaseRequestMessageOf_IlcelerIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisBeldeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisBeldelerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_BeldelerCevap> GenelServisBeldelerAsync(ServiceReference1.BaseRequestMessageOf_BeldelerIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisUlkeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisUlkelerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_UlkelerCevap> GenelServisUlkelerAsync(ServiceReference1.BaseRequestMessageOf_UlkelerIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisHalIciIsyeri", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisHalIciIsyeriResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_HalIciIsyeriCevap> GenelServisHalIciIsyeriAsync(ServiceReference1.BaseRequestMessageOf_HalIciIsyeriIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIsletmeTurleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIsletmeTurleriRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IsletmeTurleriCevap> GenelServisIsletmeTurleriAsync(ServiceReference1.BaseRequestMessageOf_IsletmeTurleriIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisDepolar", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisDepolarResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_DepolarCevap> GenelServisDepolarAsync(ServiceReference1.BaseRequestMessageOf_DepolarIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisSubeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisSubelerResponse")]
        System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_SubelerCevap> GenelServisSubelerAsync(ServiceReference1.BaseRequestMessageOf_SubelerIstek request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IllerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IllerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.IllerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IllerIstek()
        {
        }
        
        public BaseRequestMessageOf_IllerIstek(ServiceReference1.IllerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IllerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IllerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.IllerCevap Sonuc;
        
        public BaseResponseMessageOf_IllerCevap()
        {
        }
        
        public BaseResponseMessageOf_IllerCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.IllerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IlcelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IlcelerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.IlcelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IlcelerIstek()
        {
        }
        
        public BaseRequestMessageOf_IlcelerIstek(ServiceReference1.IlcelerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IlcelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IlcelerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.IlcelerCevap Sonuc;
        
        public BaseResponseMessageOf_IlcelerCevap()
        {
        }
        
        public BaseResponseMessageOf_IlcelerCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.IlcelerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_BeldelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_BeldelerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.BeldelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_BeldelerIstek()
        {
        }
        
        public BaseRequestMessageOf_BeldelerIstek(ServiceReference1.BeldelerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_BeldelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_BeldelerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.BeldelerCevap Sonuc;
        
        public BaseResponseMessageOf_BeldelerCevap()
        {
        }
        
        public BaseResponseMessageOf_BeldelerCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.BeldelerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UlkelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UlkelerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.UlkelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UlkelerIstek()
        {
        }
        
        public BaseRequestMessageOf_UlkelerIstek(ServiceReference1.UlkelerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UlkelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UlkelerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.UlkelerCevap Sonuc;
        
        public BaseResponseMessageOf_UlkelerCevap()
        {
        }
        
        public BaseResponseMessageOf_UlkelerCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.UlkelerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_HalIciIsyeriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_HalIciIsyeriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.HalIciIsyeriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_HalIciIsyeriIstek()
        {
        }
        
        public BaseRequestMessageOf_HalIciIsyeriIstek(ServiceReference1.HalIciIsyeriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_HalIciIsyeriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_HalIciIsyeriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.HalIciIsyeriCevap Sonuc;
        
        public BaseResponseMessageOf_HalIciIsyeriCevap()
        {
        }
        
        public BaseResponseMessageOf_HalIciIsyeriCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.HalIciIsyeriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IsletmeTurleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IsletmeTurleriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.IsletmeTurleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IsletmeTurleriIstek()
        {
        }
        
        public BaseRequestMessageOf_IsletmeTurleriIstek(ServiceReference1.IsletmeTurleriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IsletmeTurleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IsletmeTurleriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.IsletmeTurleriCevap Sonuc;
        
        public BaseResponseMessageOf_IsletmeTurleriCevap()
        {
        }
        
        public BaseResponseMessageOf_IsletmeTurleriCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.IsletmeTurleriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_DepolarIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_DepolarIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.DepolarIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_DepolarIstek()
        {
        }
        
        public BaseRequestMessageOf_DepolarIstek(ServiceReference1.DepolarIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_DepolarCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_DepolarCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.DepolarCevap Sonuc;
        
        public BaseResponseMessageOf_DepolarCevap()
        {
        }
        
        public BaseResponseMessageOf_DepolarCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.DepolarCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_SubelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_SubelerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.SubelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_SubelerIstek()
        {
        }
        
        public BaseRequestMessageOf_SubelerIstek(ServiceReference1.SubelerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_SubelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_SubelerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public ServiceReference1.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public ServiceReference1.SubelerCevap Sonuc;
        
        public BaseResponseMessageOf_SubelerCevap()
        {
        }
        
        public BaseResponseMessageOf_SubelerCevap(ServiceReference1.ErrorModel[] HataKodlari, string IslemKodu, ServiceReference1.SubelerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IGenelServiceChannel : ServiceReference1.IGenelService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class GenelServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IGenelService>, ServiceReference1.IGenelService
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GenelServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GenelServiceClient.GetBindingForEndpoint(endpointConfiguration), GenelServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenelServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GenelServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenelServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GenelServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GenelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IllerCevap> GenelServisIllerAsync(ServiceReference1.BaseRequestMessageOf_IllerIstek request)
        {
            return base.Channel.GenelServisIllerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IlcelerCevap> GenelServisIlcelerAsync(ServiceReference1.BaseRequestMessageOf_IlcelerIstek request)
        {
            return base.Channel.GenelServisIlcelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_BeldelerCevap> GenelServisBeldelerAsync(ServiceReference1.BaseRequestMessageOf_BeldelerIstek request)
        {
            return base.Channel.GenelServisBeldelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_UlkelerCevap> GenelServisUlkelerAsync(ServiceReference1.BaseRequestMessageOf_UlkelerIstek request)
        {
            return base.Channel.GenelServisUlkelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_HalIciIsyeriCevap> GenelServisHalIciIsyeriAsync(ServiceReference1.BaseRequestMessageOf_HalIciIsyeriIstek request)
        {
            return base.Channel.GenelServisHalIciIsyeriAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_IsletmeTurleriCevap> GenelServisIsletmeTurleriAsync(ServiceReference1.BaseRequestMessageOf_IsletmeTurleriIstek request)
        {
            return base.Channel.GenelServisIsletmeTurleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_DepolarCevap> GenelServisDepolarAsync(ServiceReference1.BaseRequestMessageOf_DepolarIstek request)
        {
            return base.Channel.GenelServisDepolarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.BaseResponseMessageOf_SubelerCevap> GenelServisSubelerAsync(ServiceReference1.BaseRequestMessageOf_SubelerIstek request)
        {
            return base.Channel.GenelServisSubelerAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGenelService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGenelService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGenelService))
            {
                return new System.ServiceModel.EndpointAddress("http://hks.hal.gov.tr/WebServices/GenelService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGenelService1))
            {
                return new System.ServiceModel.EndpointAddress("http://hks.hal.gov.tr/WebServices/GenelService.svc");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGenelService,
            
            BasicHttpBinding_IGenelService1,
        }
    }
}
