//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urunler
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class MalinNiteligiIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorModel", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Core.ServiceContract")]
    public partial class ErrorModel : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class MalinNiteligiCevap : object
    {
        
        private int HataKoduField;
        
        private Urunler.MalinNiteligiDTO[] MalinNitelikleriField;
        
        private string MesajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.MalinNiteligiDTO[] MalinNitelikleri
        {
            get
            {
                return this.MalinNitelikleriField;
            }
            set
            {
                this.MalinNitelikleriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalinNiteligiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class MalinNiteligiDTO : object
    {
        
        private int IdField;
        
        private string MalinNiteligiAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MalinNiteligiAdi
        {
            get
            {
                return this.MalinNiteligiAdiField;
            }
            set
            {
                this.MalinNiteligiAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunlerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunlerIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunlerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunlerCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private Urunler.UrunDTO[] UrunlerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.UrunDTO[] Urunler
        {
            get
            {
                return this.UrunlerField;
            }
            set
            {
                this.UrunlerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class UrunDTO : object
    {
        
        private int IdField;
        
        private string UrunAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAdi
        {
            get
            {
                return this.UrunAdiField;
            }
            set
            {
                this.UrunAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunBirimleriIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunBirimleriCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private Urunler.UrunBirimiDTO[] UrunBirimleriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.UrunBirimiDTO[] UrunBirimleri
        {
            get
            {
                return this.UrunBirimleriField;
            }
            set
            {
                this.UrunBirimleriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunBirimiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class UrunBirimiDTO : object
    {
        
        private int IdField;
        
        private string UrunBirimAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunBirimAdi
        {
            get
            {
                return this.UrunBirimAdiField;
            }
            set
            {
                this.UrunBirimAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekilleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UretimSekilleriIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekilleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UretimSekilleriCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private Urunler.UretimSekliDTO[] UretimSekilleriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.UretimSekliDTO[] UretimSekilleri
        {
            get
            {
                return this.UretimSekilleriField;
            }
            set
            {
                this.UretimSekilleriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UretimSekliDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class UretimSekliDTO : object
    {
        
        private int IdField;
        
        private string UretimSekliAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UretimSekliAdi
        {
            get
            {
                return this.UretimSekliAdiField;
            }
            set
            {
                this.UretimSekliAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunCinsleriIstek : object
    {
        
        private int UrunIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId
        {
            get
            {
                return this.UrunIdField;
            }
            set
            {
                this.UrunIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunCinsleriCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private Urunler.UrunCinsiDTO[] UrunCinsleriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.UrunCinsiDTO[] UrunCinsleri
        {
            get
            {
                return this.UrunCinsleriField;
            }
            set
            {
                this.UrunCinsleriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunCinsiDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class UrunCinsiDTO : object
    {
        
        private int IdField;
        
        private bool IthalmiField;
        
        private int UretimSekliIdField;
        
        private string UrunCinsiAdiField;
        
        private int UrunIdField;
        
        private string UrunKoduField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ithalmi
        {
            get
            {
                return this.IthalmiField;
            }
            set
            {
                this.IthalmiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UretimSekliId
        {
            get
            {
                return this.UretimSekliIdField;
            }
            set
            {
                this.UretimSekliIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunCinsiAdi
        {
            get
            {
                return this.UrunCinsiAdiField;
            }
            set
            {
                this.UrunCinsiAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId
        {
            get
            {
                return this.UrunIdField;
            }
            set
            {
                this.UrunIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunKodu
        {
            get
            {
                return this.UrunKoduField;
            }
            set
            {
                this.UrunKoduField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunMiktarBirimleriIstek : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.ServiceContract")]
    public partial class UrunMiktarBirimleriCevap : object
    {
        
        private int HataKoduField;
        
        private string MesajField;
        
        private Urunler.UrunMiktarBirimleriDTO[] UrunMiktarBirimleriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj
        {
            get
            {
                return this.MesajField;
            }
            set
            {
                this.MesajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Urunler.UrunMiktarBirimleriDTO[] UrunMiktarBirimleri
        {
            get
            {
                return this.UrunMiktarBirimleriField;
            }
            set
            {
                this.UrunMiktarBirimleriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunMiktarBirimleriDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Urun.Model")]
    public partial class UrunMiktarBirimleriDTO : object
    {
        
        private string MiktarBirimAdField;
        
        private int MiktarBirimIdField;
        
        private int UrunIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiktarBirimAd
        {
            get
            {
                return this.MiktarBirimAdField;
            }
            set
            {
                this.MiktarBirimAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MiktarBirimId
        {
            get
            {
                return this.MiktarBirimIdField;
            }
            set
            {
                this.MiktarBirimIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId
        {
            get
            {
                return this.UrunIdField;
            }
            set
            {
                this.UrunIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gtb.gov.tr//WebServices", ConfigurationName="Urunler.IUrunService")]
    public interface IUrunService
    {
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceMalinNiteligi", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceMalinNiteligiResponse")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_MalinNiteligiCevap> UrunServiceMalinNiteligiAsync(Urunler.BaseRequestMessageOf_MalinNiteligiIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunler", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunlerResponse")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunlerCevap> UrunServiceUrunlerAsync(Urunler.BaseRequestMessageOf_UrunlerIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunBirimleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunBirimleriResponse")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunBirimleriCevap> UrunServiceUrunBirimleriAsync(Urunler.BaseRequestMessageOf_UrunBirimleriIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUretimSekilleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUretimSekilleriRespons" +
            "e")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UretimSekilleriCevap> UrunServiceUretimSekilleriAsync(Urunler.BaseRequestMessageOf_UretimSekilleriIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunCinsleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunCinsleriResponse")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunCinsleriCevap> UrunServiceUrunCinsleriAsync(Urunler.BaseRequestMessageOf_UrunCinsleriIstek request);
        
        // CODEGEN: İşlemin birden fazla dönüş değeri olduğundan ileti anlaşması oluşturuluyor.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunMiktarBirimleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IUrunService/UrunServiceUrunMiktarBirimleriRes" +
            "ponse")]
        System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunMiktarBirimleriCevap> UrunServiceUrunMiktarBirimleriAsync(Urunler.BaseRequestMessageOf_UrunMiktarBirimleriIstek request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_MalinNiteligiIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_MalinNiteligiIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.MalinNiteligiIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_MalinNiteligiIstek()
        {
        }
        
        public BaseRequestMessageOf_MalinNiteligiIstek(Urunler.MalinNiteligiIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_MalinNiteligiCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_MalinNiteligiCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.MalinNiteligiCevap Sonuc;
        
        public BaseResponseMessageOf_MalinNiteligiCevap()
        {
        }
        
        public BaseResponseMessageOf_MalinNiteligiCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.MalinNiteligiCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunlerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunlerIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.UrunlerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunlerIstek()
        {
        }
        
        public BaseRequestMessageOf_UrunlerIstek(Urunler.UrunlerIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunlerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunlerCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.UrunlerCevap Sonuc;
        
        public BaseResponseMessageOf_UrunlerCevap()
        {
        }
        
        public BaseResponseMessageOf_UrunlerCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.UrunlerCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunBirimleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunBirimleriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.UrunBirimleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunBirimleriIstek()
        {
        }
        
        public BaseRequestMessageOf_UrunBirimleriIstek(Urunler.UrunBirimleriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunBirimleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunBirimleriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.UrunBirimleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunBirimleriCevap()
        {
        }
        
        public BaseResponseMessageOf_UrunBirimleriCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.UrunBirimleriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UretimSekilleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UretimSekilleriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.UretimSekilleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UretimSekilleriIstek()
        {
        }
        
        public BaseRequestMessageOf_UretimSekilleriIstek(Urunler.UretimSekilleriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UretimSekilleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UretimSekilleriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.UretimSekilleriCevap Sonuc;
        
        public BaseResponseMessageOf_UretimSekilleriCevap()
        {
        }
        
        public BaseResponseMessageOf_UretimSekilleriCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.UretimSekilleriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunCinsleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunCinsleriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.UrunCinsleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunCinsleriIstek()
        {
        }
        
        public BaseRequestMessageOf_UrunCinsleriIstek(Urunler.UrunCinsleriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunCinsleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunCinsleriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.UrunCinsleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunCinsleriCevap()
        {
        }
        
        public BaseResponseMessageOf_UrunCinsleriCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.UrunCinsleriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UrunMiktarBirimleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UrunMiktarBirimleriIstek
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.UrunMiktarBirimleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UrunMiktarBirimleriIstek()
        {
        }
        
        public BaseRequestMessageOf_UrunMiktarBirimleriIstek(Urunler.UrunMiktarBirimleriIstek Istek, string Password, string ServicePassword, string UserName)
        {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UrunMiktarBirimleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UrunMiktarBirimleriCevap
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public Urunler.ErrorModel[] HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public Urunler.UrunMiktarBirimleriCevap Sonuc;
        
        public BaseResponseMessageOf_UrunMiktarBirimleriCevap()
        {
        }
        
        public BaseResponseMessageOf_UrunMiktarBirimleriCevap(Urunler.ErrorModel[] HataKodlari, string IslemKodu, Urunler.UrunMiktarBirimleriCevap Sonuc)
        {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IUrunServiceChannel : Urunler.IUrunService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class UrunServiceClient : System.ServiceModel.ClientBase<Urunler.IUrunService>, Urunler.IUrunService
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UrunServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UrunServiceClient.GetBindingForEndpoint(endpointConfiguration), UrunServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrunServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UrunServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrunServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UrunServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrunServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_MalinNiteligiCevap> UrunServiceMalinNiteligiAsync(Urunler.BaseRequestMessageOf_MalinNiteligiIstek request)
        {
            return base.Channel.UrunServiceMalinNiteligiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunlerCevap> UrunServiceUrunlerAsync(Urunler.BaseRequestMessageOf_UrunlerIstek request)
        {
            return base.Channel.UrunServiceUrunlerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunBirimleriCevap> UrunServiceUrunBirimleriAsync(Urunler.BaseRequestMessageOf_UrunBirimleriIstek request)
        {
            return base.Channel.UrunServiceUrunBirimleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UretimSekilleriCevap> UrunServiceUretimSekilleriAsync(Urunler.BaseRequestMessageOf_UretimSekilleriIstek request)
        {
            return base.Channel.UrunServiceUretimSekilleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunCinsleriCevap> UrunServiceUrunCinsleriAsync(Urunler.BaseRequestMessageOf_UrunCinsleriIstek request)
        {
            return base.Channel.UrunServiceUrunCinsleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<Urunler.BaseResponseMessageOf_UrunMiktarBirimleriCevap> UrunServiceUrunMiktarBirimleriAsync(Urunler.BaseRequestMessageOf_UrunMiktarBirimleriIstek request)
        {
            return base.Channel.UrunServiceUrunMiktarBirimleriAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrunService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrunService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrunService))
            {
                return new System.ServiceModel.EndpointAddress("http://hks.hal.gov.tr/WebServices/UrunService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrunService1))
            {
                return new System.ServiceModel.EndpointAddress("http://hks.hal.gov.tr/WebServices/UrunService.svc");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUrunService,
            
            BasicHttpBinding_IUrunService1,
        }
    }
}
