// <auto-generated />
using System;
using MEYPAK.DAL.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEYPAK.DAL.Migrations
{
    [DbContext(typeof(MEYPAKContext))]
    [Migration("20221022132733_StokTablosundanDepoidCikarildi")]
    partial class StokTablosundanDepoidCikarildi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MEYPAK.Entity.Models.ARAC.MPARACLAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("canbusProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fleetId")
                        .HasColumnType("int");

                    b.Property<string>("fleetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hardwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("muId")
                        .HasColumnType("int");

                    b.Property<string>("networkId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("softwareSubVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("softwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MPARACLAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DEPOADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DEPOKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPO");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOCEKILIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("ISEMRIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MIKTAR")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOCEKILIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIRA")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DEPOID");

                    b.HasIndex("SIPARISID");

                    b.ToTable("MPDEPOEMIR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CIKTIDEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HEDEFDEPOID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOTRANSFER");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFERHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DEPOTRANSFERID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MIKTAR")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DEPOTRANSFERID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPDEPOTRANSFERHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKMALKABULLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BIRIMID");

                    b.HasIndex("EMIRID");

                    b.HasIndex("SIPARISDETAYID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKMALKABULLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKSEVKİYATLİST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SEVKEMRIHARID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BIRIMID");

                    b.HasIndex("EMIRID");

                    b.HasIndex("SEVKEMRIHARID");

                    b.HasIndex("SIPARISDETAYID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ALTHESAPID")
                        .HasColumnType("int");

                    b.Property<int>("ARACID")
                        .HasColumnType("int");

                    b.Property<string>("BELGENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CARIADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("EKACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<decimal>("GENELTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IRSALIYETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTOTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<bool>("KDVDAHİL")
                        .HasColumnType("bit");

                    b.Property<decimal>("KDVTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<byte>("KULLANICITIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERSONELID")
                        .HasColumnType("int");

                    b.Property<string>("SERINO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SEVKIYATTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SIPARISID");

                    b.ToTable("MPIRSALIYE");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYEDETAY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BEKLEYENMIKTAR")
                        .HasColumnType("int");

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HAREKETDURUMU")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ISTKONTO1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KDVTUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("LISTEFIYATID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<string>("STOKADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TIP")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("SIPARISID");

                    b.ToTable("MPIRSALIYEDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOEMIRSIPARISKALEMILISKI", b =>
                {
                    b.Property<int>("DEPOEMIRID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("DEPOEMIRID", "SIPARISDETAYID");

                    b.HasIndex("SIPARISDETAYID");

                    b.ToTable("MPDEPOEMIRSIPARISKALEMILISKI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPIRSALIYESIPARISDETAYILISKI", b =>
                {
                    b.Property<int>("IRSALIYEDETAYID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("IRSALIYEDETAYID", "SIPARISDETAYID");

                    b.HasIndex("SIPARISDETAYID");

                    b.ToTable("MPIRSALIYESIPARISDETAYILISKI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.PERSONEL.MPPERSONEL", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ASKERLIK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOGUMTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<string>("EHLIYETNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("GOREVI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("KANGRUBU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MEDENIDURUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PSD")
                        .HasColumnType("int");

                    b.Property<DateTime>("PSIKOTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SGKSICIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("MPPERSONEL");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ALTHESAPID")
                        .HasColumnType("int");

                    b.Property<string>("BELGENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CARIADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("EKACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<decimal>("GENELTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTOTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<bool>("KDVDAHİL")
                        .HasColumnType("bit");

                    b.Property<decimal>("KDVTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<byte>("KULLANICITIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("SERINO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SEVKIYATTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SIPARISTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DEPOID");

                    b.ToTable("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BEKLEYENMIKTAR")
                        .HasColumnType("int");

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HAREKETDURUMU")
                        .HasColumnType("tinyint");

                    b.Property<int>("IRSALIYEID")
                        .HasColumnType("int");

                    b.Property<decimal>("ISTKONTO1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KDVTUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("LISTEFIYATID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<string>("STOKADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<byte>("TIP")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("IRSALIYEID");

                    b.HasIndex("SIPARISID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISSEVKEMRIHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<decimal>("EMIRMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISKALEMID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EMIRID");

                    b.HasIndex("SIPARISID");

                    b.HasIndex("SIPARISKALEMID");

                    b.ToTable("MPSIPARISSEVKEMRIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPHIZMET", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA6")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA7")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA8")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA9")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("MPHIZMET");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BIRIM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ADOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("AFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("GRUPKODU")
                        .HasColumnType("int");

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("MARKAID")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBR1")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("RAPORKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SACIKLAMA")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA1")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA2")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA3")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA4")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA5")
                        .HasColumnType("int");

                    b.Property<decimal>("SATISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SATISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SDOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("SFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("FIYATLISTADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLISTHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AKTIF")
                        .HasColumnType("int");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIYATLISTID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FIYATLISTID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKFIYATLISTHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BELGE_NO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BIRIM")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FATURAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HAREKETTURU")
                        .HasColumnType("int");

                    b.Property<int>("IO")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKKASA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("AKTIF")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("KASAADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KASAKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKKASA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKKATEGORI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AltID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("UstId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKKATEGORI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKMARKA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPMARKA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KATSAYI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBRID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OLCUBRID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SAYIMTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKSAYIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIMHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<decimal>("FIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PARABR")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("STOKSAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BIRIMID");

                    b.HasIndex("STOKID");

                    b.HasIndex("STOKSAYIMID");

                    b.ToTable("MPSTOKSAYIMHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPO", "MPDEPO")
                        .WithMany("MPDEPOEMIR")
                        .HasForeignKey("DEPOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", "MPSIPARIS")
                        .WithMany("MPDEPOEMIR")
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MPDEPO");

                    b.Navigation("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFERHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFER", "MPDEPOTRANSFER")
                        .WithMany()
                        .HasForeignKey("DEPOTRANSFERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany()
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPDEPOTRANSFER");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKMALKABULLIST", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKMALKABULLIST")
                        .HasForeignKey("BIRIMID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", "MPDEPOEMIR")
                        .WithMany("MPSTOKMALKABULLIST")
                        .HasForeignKey("EMIRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", "MPSIPARISDETAY")
                        .WithMany("MPSTOKMALKABULLIST")
                        .HasForeignKey("SIPARISDETAYID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKMALKABULLIST")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MPDEPOEMIR");

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSIPARISDETAY");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKSEVKİYATLİST", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKSEVKİYATLİST")
                        .HasForeignKey("BIRIMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", "MPDEPOEMIR")
                        .WithMany("MPSTOKSEVKİYATLİST")
                        .HasForeignKey("EMIRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISSEVKEMRIHAR", "MPSIPARISSEVKEMRIHAR")
                        .WithMany("MPSTOKSEVKİYATLİST")
                        .HasForeignKey("SEVKEMRIHARID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", "MPSIPARISDETAY")
                        .WithMany("MPSTOKSEVKİYATLİST")
                        .HasForeignKey("SIPARISDETAYID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKSEVKİYATLİST")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPDEPOEMIR");

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSIPARISDETAY");

                    b.Navigation("MPSIPARISSEVKEMRIHAR");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYE", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", "MPSIPARIS")
                        .WithMany("MPIRSALIYE")
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYEDETAY", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", "MPSIPARIS")
                        .WithMany()
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOEMIRSIPARISKALEMILISKI", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", "MPDEPOEMIR")
                        .WithMany("MPDEPOEMIRSIPARISKALEMILISKI")
                        .HasForeignKey("DEPOEMIRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", "MPSIPARISDETAY")
                        .WithMany("MPDEPOEMIRSIPARISKALEMILISKI")
                        .HasForeignKey("SIPARISDETAYID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MPDEPOEMIR");

                    b.Navigation("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPIRSALIYESIPARISDETAYILISKI", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYEDETAY", "MPIRSALIYEDETAY")
                        .WithMany("MPIRSALIYESIPARISDETAYILISKI")
                        .HasForeignKey("IRSALIYEDETAYID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", "MPSIPARISDETAY")
                        .WithMany("MPIRSALIYESIPARISDETAYILISKI")
                        .HasForeignKey("SIPARISDETAYID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MPIRSALIYEDETAY");

                    b.Navigation("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPO", "MPDEPO")
                        .WithMany()
                        .HasForeignKey("DEPOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPDEPO");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYE", "MPIRSALIYE")
                        .WithMany()
                        .HasForeignKey("IRSALIYEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", "MPSIPARIS")
                        .WithMany("MPSIPARISDETAY")
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSIPARISDETAY")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MPIRSALIYE");

                    b.Navigation("MPSIPARIS");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISSEVKEMRIHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", "MPDEPOEMIR")
                        .WithMany("MPSIPARISSEVKEMRIHAR")
                        .HasForeignKey("EMIRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", "MPSIPARIS")
                        .WithMany("MPSIPARISSEVKEMRIHAR")
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", "MPSIPARISDETAY")
                        .WithMany("MPSIPARISSEVKEMRIHAR")
                        .HasForeignKey("SIPARISKALEMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPDEPOEMIR");

                    b.Navigation("MPSIPARIS");

                    b.Navigation("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLISTHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLIST", "MPSTOKFIYATLIST")
                        .WithMany("MPSTOKFIYATLISTHAR")
                        .HasForeignKey("FIYATLISTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKFIYATLISTHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSTOK");

                    b.Navigation("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKOLCUBR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKOLCUBR")
                        .HasForeignKey("OLCUBRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKOLCUBR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIMHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.STOK.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("BIRIMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.STOK.MPSTOKSAYIM", "MPSTOKSAYIM")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("STOKSAYIMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSTOK");

                    b.Navigation("MPSTOKSAYIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPO", b =>
                {
                    b.Navigation("MPDEPOEMIR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", b =>
                {
                    b.Navigation("MPDEPOEMIRSIPARISKALEMILISKI");

                    b.Navigation("MPSIPARISSEVKEMRIHAR");

                    b.Navigation("MPSTOKMALKABULLIST");

                    b.Navigation("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYEDETAY", b =>
                {
                    b.Navigation("MPIRSALIYESIPARISDETAYILISKI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", b =>
                {
                    b.Navigation("MPDEPOEMIR");

                    b.Navigation("MPIRSALIYE");

                    b.Navigation("MPSIPARISDETAY");

                    b.Navigation("MPSIPARISSEVKEMRIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", b =>
                {
                    b.Navigation("MPDEPOEMIRSIPARISKALEMILISKI");

                    b.Navigation("MPIRSALIYESIPARISDETAYILISKI");

                    b.Navigation("MPSIPARISSEVKEMRIHAR");

                    b.Navigation("MPSTOKMALKABULLIST");

                    b.Navigation("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISSEVKEMRIHAR", b =>
                {
                    b.Navigation("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPOLCUBR", b =>
                {
                    b.Navigation("MPSTOKMALKABULLIST");

                    b.Navigation("MPSTOKOLCUBR");

                    b.Navigation("MPSTOKSAYIMHAR");

                    b.Navigation("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOK", b =>
                {
                    b.Navigation("MPSIPARISDETAY");

                    b.Navigation("MPSTOKFIYATLISTHAR");

                    b.Navigation("MPSTOKHAR");

                    b.Navigation("MPSTOKMALKABULLIST");

                    b.Navigation("MPSTOKOLCUBR");

                    b.Navigation("MPSTOKSAYIMHAR");

                    b.Navigation("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLIST", b =>
                {
                    b.Navigation("MPSTOKFIYATLISTHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIM", b =>
                {
                    b.Navigation("MPSTOKSAYIMHAR");
                });
#pragma warning restore 612, 618
        }
    }
}
