// <auto-generated />
using System;
using MEYPAK.DAL.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEYPAK.DAL.Migrations
{
    [DbContext(typeof(MEYPAKContext))]
    [Migration("20221108094710_CariAltHesapPropAdded")]
    partial class CariAltHesapPropAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MEYPAK.Entity.IdentityModels.MPROLE", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("MEYPAK.Entity.IdentityModels.MPUSER", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SOYAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.ARAC.MPARACLAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("canbusProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fleetId")
                        .HasColumnType("int");

                    b.Property<string>("fleetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hardwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("muId")
                        .HasColumnType("int");

                    b.Property<string>("networkId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("softwareSubVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("softwareVersion")
                        .HasColumnType("int");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MPARACLAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.CARI.MPCARIALTHES", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("AKTIF")
                        .HasColumnType("tinyint");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPCARIALTHES");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.CARI.MPCARIHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ALACAK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BELGE_NO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BORC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HAREKETTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HAREKETTIPI")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PARABIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("TUTAR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("MPCARIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.CARI.MPCARIKART", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACIKLAMA9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AMUHKOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEPTEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAIRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPOSTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("FAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FIYATNUM")
                        .HasColumnType("int");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("IL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ILCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KATEGORI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAHALLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUH_KOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("POSTAKOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAPORKOD9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SACIKLAMA1")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA2")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA3")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA4")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA5")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA6")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA7")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA8")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA9")
                        .HasColumnType("int");

                    b.Property<string>("SMUHKOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOKAK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFON2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TIPI")
                        .HasColumnType("int");

                    b.Property<string>("UNVAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<string>("VERGIDAIRESI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERGINO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MPCARIKART");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DEPOADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DEPOKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPO");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOCEKILIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("ISEMRIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MIKTAR")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOCEKILIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOEMIR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIRA")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOEMIR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CIKTIDEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HEDEFDEPOID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOTRANSFER");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPDEPOTRANSFERHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DEPOTRANSFERID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MIKTAR")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPDEPOTRANSFERHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKMALKABULLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SATINALMAMALKABULEMRIHARID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKMALKABULLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.DEPO.MPSTOKSEVKİYATLİST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SEVKEMRIHARID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKSEVKİYATLİST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ALTHESAPID")
                        .HasColumnType("int");

                    b.Property<int>("ARACID")
                        .HasColumnType("int");

                    b.Property<string>("BELGENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CARIADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("EKACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<decimal>("GENELTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IRSALIYETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTOTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<bool>("KDVDAHİL")
                        .HasColumnType("bit");

                    b.Property<decimal>("KDVTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<byte>("KULLANICITIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERSONELID")
                        .HasColumnType("int");

                    b.Property<string>("SERINO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SEVKIYATTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPIRSALIYE");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.IRSALIYE.MPIRSALIYEDETAY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BEKLEYENMIKTAR")
                        .HasColumnType("int");

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HAREKETDURUMU")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ISTKONTO1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KDVTUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("LISTEFIYATID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<string>("STOKADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TIP")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("MPIRSALIYEDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPIRSALIYESIPARISDETAYILISKI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("IRSALIYEDETAYID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISDETAYID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPIRSALIYESIPARISDETAYILISKI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.PARAMETRE.MPPARABIRIM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("AKTIF")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KISAADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPPARABIRIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.PERSONEL.MPPERSONEL", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ASKERLIK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOGUMTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<string>("EHLIYETNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("GOREVI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("KANGRUBU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MEDENIDURUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PSD")
                        .HasColumnType("int");

                    b.Property<DateTime>("PSIKOTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SGKSICIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("MPPERSONEL");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSATINALMAMALKABULEMRIHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<decimal>("EMIRMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISKALEMID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSATINALMAMALKABULEMRIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARIS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ALTHESAPID")
                        .HasColumnType("int");

                    b.Property<string>("BELGENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CARIADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("EKACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<decimal>("GENELTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTOTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<bool>("KDVDAHİL")
                        .HasColumnType("bit");

                    b.Property<decimal>("KDVTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<byte>("KULLANICITIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("SERINO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SEVKIYATTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SIPARISTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISDETAY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BEKLEYENMIKTAR")
                        .HasColumnType("int");

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HAREKETDURUMU")
                        .HasColumnType("tinyint");

                    b.Property<int>("IRSALIYEID")
                        .HasColumnType("int");

                    b.Property<decimal>("ISTKONTO1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KDVTUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("LISTEFIYATID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<string>("STOKADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<byte>("TIP")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.SIPARIS.MPSIPARISSEVKEMRIHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<decimal>("EMIRMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISKALEMID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSIPARISSEVKEMRIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPHIZMET", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA6")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA7")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA8")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA9")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("MPHIZMET");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BIRIM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ADOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("AFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KASAID")
                        .HasColumnType("int");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("MARKAID")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBR1")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("RAPORKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SACIKLAMA")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA1")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA2")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA3")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA4")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA5")
                        .HasColumnType("int");

                    b.Property<decimal>("SATISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SATISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SDOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("SFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<string>("FIYATLISTADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKFIYATLISTHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AKTIF")
                        .HasColumnType("int");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIYATLISTID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKFIYATLISTHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BELGE_NO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BIRIM")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FATURAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HAREKETTURU")
                        .HasColumnType("int");

                    b.Property<int>("IO")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKKASA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("AKTIF")
                        .HasColumnType("tinyint");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("KASAADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KASAKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKKASA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKKATEGORI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AltID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("UstId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKKATEGORI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKMARKA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKMARKA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KATSAYI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBRID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SAYIMTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKSAYIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.STOK.MPSTOKSAYIMHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("ESKIID")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<decimal>("FIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PARABR")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("STOKSAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKSAYIMHAR");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MEYPAK.Entity.IdentityModels.MPROLE", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MEYPAK.Entity.IdentityModels.MPUSER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MEYPAK.Entity.IdentityModels.MPUSER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MEYPAK.Entity.IdentityModels.MPROLE", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.IdentityModels.MPUSER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MEYPAK.Entity.IdentityModels.MPUSER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
