// <auto-generated />
using System;
using MEYPAK.DAL.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEYPAK.DAL.Migrations
{
    [DbContext(typeof(MEYPAKContext))]
    [Migration("20220929131242_MEYPAKPersonelDuzenleme")]
    partial class MEYPAKPersonelDuzenleme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MEYPAK.Entity.Models.MPARACLAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ARACKM")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("MARKA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MODEL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MUAYENETAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OLUTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERSONELID")
                        .HasColumnType("int");

                    b.Property<string>("PLAKA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SERVISTAR")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("YIL")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPARACLAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("")
                        .HasColumnOrder(7);

                    b.Property<string>("DEPOADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<string>("DEPOKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("IL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnOrder(8);

                    b.Property<string>("ILCE")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnOrder(9);

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("ULKE")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnOrder(10);

                    b.HasKey("ID");

                    b.ToTable("MPDEPO");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPHIZMET", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA6")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA7")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA8")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA9")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("MPHIZMET");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPMARKA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KAYITTIPI")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPMARKA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIRIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KAYITTIPI")
                        .HasColumnType("int");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPPERSONEL", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ASKERLIK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOGUMTAR")
                        .HasColumnType("datetime2");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<string>("EHLIYETNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GOREVI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ISBASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("KANGRUBU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KAYITTIPI")
                        .HasColumnType("int");

                    b.Property<int>("MEDENIDURUM")
                        .HasColumnType("int");

                    b.Property<int>("PSD")
                        .HasColumnType("int");

                    b.Property<DateTime>("PSIKOTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SGKSICIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("MPPERSONEL");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("AFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("GRUPKODU")
                        .HasColumnType("int");

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("MARKAID")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBRID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("RAPORKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SACIKLAMA")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA1")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA2")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA3")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA4")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA5")
                        .HasColumnType("int");

                    b.Property<decimal>("SATISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SATISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKFIYATLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AKTIF")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KAYITTIPI")
                        .HasColumnType("int");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BELGE_NO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BIRIM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("FATURAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HAREKETTURU")
                        .HasColumnType("int");

                    b.Property<decimal>("ISKONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PALETTIPI")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KATSAYI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int?>("MPSTOKID")
                        .HasColumnType("int");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MPSTOKID");

                    b.ToTable("MPSTOKOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKOLCUBR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", null)
                        .WithMany("MPSTOKOLCUBR")
                        .HasForeignKey("MPSTOKID");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOK", b =>
                {
                    b.Navigation("MPSTOKOLCUBR");
                });
#pragma warning restore 612, 618
        }
    }
}
