// <auto-generated />
using System;
using MEYPAK.DAL.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEYPAK.DAL.Migrations
{
    [DbContext(typeof(MEYPAKContext))]
    [Migration("20221010074648_MEYPAKDepoGuncelleme2")]
    partial class MEYPAKDepoGuncelleme2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MEYPAK.Entity.Models.MPARACLAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ARACKM")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("MARKA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MODEL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("MUAYENETAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OLUTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PERSONELID")
                        .HasColumnType("int");

                    b.Property<string>("PLAKA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SERVISTAR")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("YIL")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPARACLAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(7);

                    b.Property<string>("DEPOADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<string>("DEPOKODU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("ID");

                    b.ToTable("MPDEPO");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOEMIR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIRA")
                        .HasColumnType("int");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<int>("TIP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SIPARISID");

                    b.ToTable("MPDEPOEMIR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOTRANSFER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CIKTIDEPOID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<int>("HEDEFDEPOID")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.HasKey("ID");

                    b.ToTable("MPDEPOTRANSFER");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOTRANSFERHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(7);

                    b.Property<int>("DEPOTRANSFERID")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(8);

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MIKTAR")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<int>("STOKID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("ID");

                    b.HasIndex("DEPOTRANSFERID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPDEPOTRANSFERHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPHIZMET", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA6")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA7")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA8")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA9")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRUPKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("MPHIZMET");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPKATEGORI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AltID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("UstId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPKATEGORI");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPMARKA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPMARKA");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BIRIM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPPERSONEL", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ADRES")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ASKERLIK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DOGUMTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DURUM")
                        .HasColumnType("tinyint");

                    b.Property<string>("EHLIYETNO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GOREVI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ISBASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ISBITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("KANGRUBU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("MEDENIDURUM")
                        .HasColumnType("int");

                    b.Property<int>("PSD")
                        .HasColumnType("int");

                    b.Property<DateTime>("PSIKOTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESIM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SGKSICIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<string>("SOYADI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("MPPERSONEL");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSIPARIS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ALTHESAPID")
                        .HasColumnType("int");

                    b.Property<string>("BELGENO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CARIADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CARIID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<bool>("DURUM")
                        .HasColumnType("bit");

                    b.Property<string>("EKACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GENELTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTOTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<bool>("KDVDAHİL")
                        .HasColumnType("bit");

                    b.Property<decimal>("KDVTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<byte>("KULLANICITIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("SERINO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SEVKIYATTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SIPARISTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.Property<int>("VADEGUNU")
                        .HasColumnType("int");

                    b.Property<DateTime>("VADETARIHI")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSIPARISDETAY", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BEKLEYENMIKTAR")
                        .HasColumnType("int");

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HAREKETDURUMU")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ISTKONTO1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISTKONTO3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KDVTUTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("LISTEFIYATID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<string>("STOKADI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<byte>("TIP")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("SIPARISID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSIPARISSEVKEMRIHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("BEKLEYENMIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DEPOMIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EMIRID")
                        .HasColumnType("int");

                    b.Property<decimal>("EMIRMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISID")
                        .HasColumnType("int");

                    b.Property<int>("SIPARISKALEMID")
                        .HasColumnType("int");

                    b.Property<decimal>("SIPARISMIKTARI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TARIH")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MPSIPARISSEVKEMRIHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOK", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ACIKLAMA1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ACIKLAMA5")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ADOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("AFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ALISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GRUPKODU")
                        .HasColumnType("int");

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("KATEGORIID")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<string>("KOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("MARKAID")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBR1")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("RAPORKODU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RAPORKODU9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SACIKLAMA")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA1")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA2")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA3")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA4")
                        .HasColumnType("int");

                    b.Property<int>("SACIKLAMA5")
                        .HasColumnType("int");

                    b.Property<decimal>("SATISKDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SATISOTV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SDOVIZID")
                        .HasColumnType("int");

                    b.Property<decimal>("SFIYAT1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SFIYAT5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKFIYATLIST", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BASTAR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BITTAR")
                        .HasColumnType("datetime2");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIYATLISTADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKFIYATLISTHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AKTIF")
                        .HasColumnType("int");

                    b.Property<int>("DOVIZID")
                        .HasColumnType("int");

                    b.Property<int>("FIYATLISTID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ISKONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FIYATLISTID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKFIYATLISTHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BELGE_NO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BIRIM")
                        .HasColumnType("int");

                    b.Property<decimal>("BRUTTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("FATURAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("HAREKETTURU")
                        .HasColumnType("int");

                    b.Property<int>("IO")
                        .HasColumnType("int");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETFIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NETTOPLAM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SIRKETID")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKOLCUBR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KATSAYI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<int>("KULLANICIID")
                        .HasColumnType("int");

                    b.Property<int>("NUM")
                        .HasColumnType("int");

                    b.Property<int>("OLCUBRID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OLCUBRID");

                    b.HasIndex("STOKID");

                    b.ToTable("MPSTOKOLCUBR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKSAYIM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("DURUM")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SAYIMTARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("MPSTOKSAYIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKSAYIMHAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BIRIMID")
                        .HasColumnType("int");

                    b.Property<int>("DEPOID")
                        .HasColumnType("int");

                    b.Property<int>("FIRMAID")
                        .HasColumnType("int");

                    b.Property<decimal>("FIYAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GUNCELLEMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<byte>("KAYITTIPI")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("KUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MIKTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OLUSTURMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<int>("PARABR")
                        .HasColumnType("int");

                    b.Property<int>("STOKID")
                        .HasColumnType("int");

                    b.Property<int>("STOKSAYIMID")
                        .HasColumnType("int");

                    b.Property<int>("SUBEID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BIRIMID");

                    b.HasIndex("STOKID");

                    b.HasIndex("STOKSAYIMID");

                    b.ToTable("MPSTOKSAYIMHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOEMIR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPSIPARIS", "MPSIPARIS")
                        .WithMany()
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSIPARIS");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPDEPOTRANSFERHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPDEPOTRANSFER", "DEPOTRANSFER")
                        .WithMany()
                        .HasForeignKey("DEPOTRANSFERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "STOK")
                        .WithMany()
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEPOTRANSFER");

                    b.Navigation("STOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSIPARISDETAY", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPSIPARIS", "MPSIPARIS")
                        .WithMany("MPSIPARISDETAY")
                        .HasForeignKey("SIPARISID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "MPSTOK")
                        .WithMany("MPSIPARISDETAY")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSIPARIS");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKFIYATLISTHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPSTOKFIYATLIST", "MPSTOKFIYATLIST")
                        .WithMany("MPSTOKFIYATLISTHAR")
                        .HasForeignKey("FIYATLISTID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKFIYATLISTHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSTOK");

                    b.Navigation("MPSTOKFIYATLIST");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKOLCUBR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKOLCUBR")
                        .HasForeignKey("OLCUBRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKOLCUBR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSTOK");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKSAYIMHAR", b =>
                {
                    b.HasOne("MEYPAK.Entity.Models.MPOLCUBR", "MPOLCUBR")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("BIRIMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOK", "MPSTOK")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("STOKID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEYPAK.Entity.Models.MPSTOKSAYIM", "MPSTOKSAYIM")
                        .WithMany("MPSTOKSAYIMHAR")
                        .HasForeignKey("STOKSAYIMID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MPOLCUBR");

                    b.Navigation("MPSTOK");

                    b.Navigation("MPSTOKSAYIM");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPOLCUBR", b =>
                {
                    b.Navigation("MPSTOKOLCUBR");

                    b.Navigation("MPSTOKSAYIMHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSIPARIS", b =>
                {
                    b.Navigation("MPSIPARISDETAY");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOK", b =>
                {
                    b.Navigation("MPSIPARISDETAY");

                    b.Navigation("MPSTOKFIYATLISTHAR");

                    b.Navigation("MPSTOKHAR");

                    b.Navigation("MPSTOKOLCUBR");

                    b.Navigation("MPSTOKSAYIMHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKFIYATLIST", b =>
                {
                    b.Navigation("MPSTOKFIYATLISTHAR");
                });

            modelBuilder.Entity("MEYPAK.Entity.Models.MPSTOKSAYIM", b =>
                {
                    b.Navigation("MPSTOKSAYIMHAR");
                });
#pragma warning restore 612, 618
        }
    }
}
